<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>79e4b15e-7fcb-4ca9-ad6c-4b951a8e9d03</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.6.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\SolicitudAnticipos.Domain\SolicitudAnticipos.Domain.csproj" />
    <ProjectReference Include="..\SolicitudAnticipos.Infrastructure\SolicitudAnticipos.Infrastructure.csproj" />
  </ItemGroup>

</Project>
