// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SolicitudAnticipos.Infrastructure.Persistencia;

#nullable disable

namespace SolicitudAnticipos.Infrastructure.Persistencia.Migraciones
{
    [DbContext(typeof(SolicitudAnticiposDbContext))]
    partial class SolicitudAnticiposDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SolicitudAnticipos.Domain.Entities.Adjunto", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("FechaCarga")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_carga");

                    b.Property<string>("NombreArchivo")
                        .IsRequired()
                        .HasMaxLength(260)
                        .HasColumnType("character varying(260)")
                        .HasColumnName("nombre_archivo");

                    b.Property<Guid>("SolicitudId")
                        .HasColumnType("uuid")
                        .HasColumnName("solicitud_id");

                    b.Property<string>("TipoContenido")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("tipo_contenido");

                    b.Property<string>("UrlSharePoint")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("url_share_point");

                    b.HasKey("Id")
                        .HasName("pk_adjuntos");

                    b.HasIndex("SolicitudId")
                        .HasDatabaseName("ix_adjuntos_solicitud_id");

                    b.ToTable("adjuntos", (string)null);
                });

            modelBuilder.Entity("SolicitudAnticipos.Domain.Entities.EventoBitacora", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Detalle")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("detalle");

                    b.Property<DateTimeOffset>("Fecha")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha");

                    b.Property<Guid>("SolicitudId")
                        .HasColumnType("uuid")
                        .HasColumnName("solicitud_id");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("tipo");

                    b.HasKey("Id")
                        .HasName("pk_bitacora_eventos");

                    b.HasIndex("SolicitudId")
                        .HasDatabaseName("ix_bitacora_eventos_solicitud_id");

                    b.ToTable("bitacora_eventos", (string)null);
                });

            modelBuilder.Entity("SolicitudAnticipos.Domain.Entities.MatrizAprobacion", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean")
                        .HasColumnName("activo");

                    b.Property<string>("AprobadorEmail")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("aprobador_email");

                    b.Property<string>("AprobadorNombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("aprobador_nombre");

                    b.Property<string>("Departamento")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("departamento");

                    b.Property<bool>("EsAnalistaFinanciero")
                        .HasColumnType("boolean")
                        .HasColumnName("es_analista_financiero");

                    b.Property<int>("Nivel")
                        .HasColumnType("integer")
                        .HasColumnName("nivel");

                    b.Property<int>("Orden")
                        .HasColumnType("integer")
                        .HasColumnName("orden");

                    b.HasKey("Id")
                        .HasName("pk_matrices_aprobacion");

                    b.HasIndex("Departamento", "Activo")
                        .HasDatabaseName("ix_matrices_aprobacion_departamento_activo");

                    b.ToTable("matrices_aprobacion", (string)null);
                });

            modelBuilder.Entity("SolicitudAnticipos.Domain.Entities.PasoAprobacion", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AprobadorEmail")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("aprobador_email");

                    b.Property<string>("AprobadorNombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("aprobador_nombre");

                    b.Property<string>("Comentario")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("comentario");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("estado");

                    b.Property<DateTimeOffset?>("FechaLimite")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_limite");

                    b.Property<DateTimeOffset?>("FechaNotificacion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_notificacion");

                    b.Property<DateTimeOffset?>("FechaRespuesta")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_respuesta");

                    b.Property<int>("Nivel")
                        .HasColumnType("integer")
                        .HasColumnName("nivel");

                    b.Property<int>("Orden")
                        .HasColumnType("integer")
                        .HasColumnName("orden");

                    b.Property<Guid>("SolicitudId")
                        .HasColumnType("uuid")
                        .HasColumnName("solicitud_id");

                    b.Property<string>("TokenAprobacion")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("token_aprobacion");

                    b.HasKey("Id")
                        .HasName("pk_pasos_aprobacion");

                    b.HasIndex("SolicitudId")
                        .HasDatabaseName("ix_pasos_aprobacion_solicitud_id");

                    b.HasIndex("TokenAprobacion")
                        .IsUnique()
                        .HasDatabaseName("ix_pasos_aprobacion_token_aprobacion");

                    b.ToTable("pasos_aprobacion", (string)null);
                });

            modelBuilder.Entity("SolicitudAnticipos.Domain.Entities.Solicitud", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ComentarioResolucion")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("comentario_resolucion");

                    b.Property<string>("Departamento")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("departamento");

                    b.Property<bool>("EsUrgente")
                        .HasColumnType("boolean")
                        .HasColumnName("es_urgente");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("estado");

                    b.Property<DateTimeOffset>("FechaActualizacion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_actualizacion");

                    b.Property<DateTimeOffset>("FechaCreacion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_creacion");

                    b.Property<string>("FormsResponseId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("forms_response_id");

                    b.Property<bool>("IncluyeAnalistaFinanciero")
                        .HasColumnType("boolean")
                        .HasColumnName("incluye_analista_financiero");

                    b.Property<string>("ModoAprobacion")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("modo_aprobacion");

                    b.Property<decimal>("Monto")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("monto");

                    b.Property<string>("NombreResolutor")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("nombre_resolutor");

                    b.Property<string>("Sociedad")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("sociedad");

                    b.Property<string>("SolicitanteEmail")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("solicitante_email");

                    b.Property<string>("SolicitanteNombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("solicitante_nombre");

                    b.HasKey("Id")
                        .HasName("pk_solicitudes");

                    b.HasIndex("FormsResponseId")
                        .IsUnique()
                        .HasDatabaseName("ix_solicitudes_forms_response_id");

                    b.ToTable("solicitudes", (string)null);
                });

            modelBuilder.Entity("SolicitudAnticipos.Domain.Entities.Adjunto", b =>
                {
                    b.HasOne("SolicitudAnticipos.Domain.Entities.Solicitud", null)
                        .WithMany("Adjuntos")
                        .HasForeignKey("SolicitudId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_adjuntos_solicitudes_solicitud_id");
                });

            modelBuilder.Entity("SolicitudAnticipos.Domain.Entities.EventoBitacora", b =>
                {
                    b.HasOne("SolicitudAnticipos.Domain.Entities.Solicitud", null)
                        .WithMany("Bitacora")
                        .HasForeignKey("SolicitudId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_bitacora_eventos_solicitudes_solicitud_id");
                });

            modelBuilder.Entity("SolicitudAnticipos.Domain.Entities.PasoAprobacion", b =>
                {
                    b.HasOne("SolicitudAnticipos.Domain.Entities.Solicitud", null)
                        .WithMany("Pasos")
                        .HasForeignKey("SolicitudId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_pasos_aprobacion_solicitudes_solicitud_id");
                });

            modelBuilder.Entity("SolicitudAnticipos.Domain.Entities.Solicitud", b =>
                {
                    b.Navigation("Adjuntos");

                    b.Navigation("Bitacora");

                    b.Navigation("Pasos");
                });
#pragma warning restore 612, 618
        }
    }
}
